# Generated by Django 4.1 on 2022-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
