# Generated by Django 4.1 on 2022-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_ordered_date_alter_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
