# Generated by Django 4.1 on 2022-08-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_ordered_date_alter_order_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-ordered_date"], "verbose_name_plural": "Orders"},
        ),
    ]
