requirements:
	pip install -r requirements.txt

serve:
	python3 manage.py runserver

migrations:
	python manage.py makemigrations
	python manage.py migrate

superuser:
	python manage.py createsuperuser